---
- name: Create OpenStack Instances
  hosts: localhost
  gather_facts: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: Create Instance
      openstack.cloud.server:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        config_drive: True
        key_name: "{{ item.keypair }}"
        flavor: "{{ item.flavor }}"
        security_groups: "{{ item.security_group }}"
        auto_ip: no
        wait: no
        nics:
          - net-name: "{{ item.internal_network }}"
        meta:
          AnsibleGroup: "{{ item.metadata.AnsibleGroup }}"
          type: "{{ item.metadata.type }}"
        state: present
      register: servers
      loop: "{{ instances }}"
      async: 7200
      poll: 0
  
    - name: Wait for instance(s) creation to complete
      vars:
        ansible_async_dir: "{{ lookup('env','HOME') }}/.ansible_async/"
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: os_jobs
      until: os_jobs.finished
      retries: 300
      loop: "{{ servers.results | flatten(levels=1) }}"
